services:
  db:
    image: mysql:8.0.27
    environment:
      MYSQL_DATABASE: ies
      MYSQL_USER: ies
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
        test: mysqladmin ping -h localhost
        interval: 30s
        timeout: 10s
        retries: 5  

  backend:
    build: ./projBackend/finance
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ies
      SPRING_DATASOURCE_USERNAME: ies
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:alpine
    healthcheck:
        test: rabbitmq-diagnostics -q status
        interval: 30s
        timeout: 10s
        retries: 5

  client:
    build: ./projFrontend
    ports:
      - 4200:80
    depends_on:
      - backend
    
  data_gen:
    build: ./projDataGenerator/
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links: 
        - rabbitmq